version: "3.3"
networks:
  lnnet:

volumes: 
  lnd-rest:
    
services:
  bitcoind:
    container_name: bitcoind
    build:
        context: bitcoind
    image: lyn/bitcoind:latest
    networks:
      - lnnet
    expose:
      - "18443"
      - "12005"
      - "12006"
    ports:
      - "0.0.0.0:18443:18443"
    restart: always

  lnd-node:
    container_name: lnd-node
    build:
        context: lnd
    image: lyn/lnd:latest
    networks:
      - lnnet
    expose:
      - "9732"
    ports:
      - "0.0.0.0:9732:9732"
    restart: always

  c-lightning-node:
    container_name: c-lightning-node
    hostname: lightning
    build:
      context: c-lightning
    image: lyn/c-lightning:latest
    networks:
      - lnnet
    volumes:
      - lnd-rest:/rest  
    expose:
      - "3002"
      - "4001"
      - "9730"
    ports:
      - "0.0.0.0:9730:9730"
    restart: always

  eclair-node:
    container_name: eclair-node
    build:
        context: eclair
    image: lyn/eclair:latest
    networks:
      - lnnet
    expose:
      - "9731"
    ports:
      - "0.0.0.0:9731:9731"
    restart: always

  c-lightning-ui:
    container_name: c-lightning-ui
    image: dangershony/clnd-rtl:latest
    hostname: c-lightning-ui
    networks:
      - lnnet
    volumes:
      - lnd-rest:/rest
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - "c-lightning-node"